### ISSUE TITLE
Not storing Yata json properly

### ISSUE THREAD

**Issue by Sandbird** [sid-the-sloth1/yata-scripts#4]
Shouldn't the retrieve function be like
`sessionStorage.setItem('hardy_travel_data', JSON.stringify(e.responseText));`
At least in Chrome the above works.

On my pc having it like:
`sessionStorage.setItem('hardy_travel_data', e.responseText);`
isnt working (Chrome and FF)

**Comment by sid-the-sloth1** [comment]
Thanks for pointing it out. Pushed the change. Lemme know if it works out for you.

**Comment by Sandbird** [comment]
Awesome :) thanks man. All good!
